"""empty message

Revision ID: ab65fd5bf21b
Revises: 4c200786459d
Create Date: 2021-01-24 00:21:27.869996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab65fd5bf21b'
down_revision = '4c200786459d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['genre_name'], ['genres.name'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_genres')
    # ### end Alembic commands ###
